version: '3'
services:
  web:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: .
      dockerfile: dockerfile.dev
    
    volumes:
      - .:/app

  test:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: .
      dockerfile: dockerfile.dev
    volumes:
      - .:/app
    command: ["npm", "run", "test"]
